//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTW_Project
{
    using Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        [Display(Name = "Question", ResourceType = typeof(MyTexts))]
        public int QuestionID { get; set; }
        [Display(Name = "Answer", ResourceType = typeof(MyTexts))]
        public string Answer { get; set; }
        public int IsLocked { get; set; }
        [Display(Name = "Password", ResourceType = typeof(MyTexts))]
        public string Password { get; set; }
        public int UserTypeID { get; set; }
        public Nullable<int> LoginCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Question Question { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
