//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTW_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPasswordRequest
    {
        public int id { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int Flag { get; set; }
        public int ClientID { get; set; }
    }
}
