//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTW_Project.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTW_Project.Resources.MyTexts", typeof(MyTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL Orders.
        /// </summary>
        public static string ALLOrders {
            get {
                return ResourceManager.GetString("ALLOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Stocks:.
        /// </summary>
        public static string AllStocks {
            get {
                return ResourceManager.GetString("AllStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is Required.
        /// </summary>
        public static string AnswerRequired {
            get {
                return ResourceManager.GetString("AnswerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent an E-mail. please check your E-mail.
        /// </summary>
        public static string CheckSent {
            get {
                return ResourceManager.GetString("CheckSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Question.
        /// </summary>
        public static string ChooseQuestion {
            get {
                return ResourceManager.GetString("ChooseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email isn&apos;t Valied.
        /// </summary>
        public static string EmailisNotValied {
            get {
                return ResourceManager.GetString("EmailisNotValied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Answer.
        /// </summary>
        public static string EnterYourAnswer {
            get {
                return ResourceManager.GetString("EnterYourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Password.
        /// </summary>
        public static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length is 20 charachters.
        /// </summary>
        public static string FirstNameLength {
            get {
                return ResourceManager.GetString("FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is Required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order ID you entered isn&apos;t correct, please make sure of the ID and Research again.
        /// </summary>
        public static string IDNotValied {
            get {
                return ResourceManager.GetString("IDNotValied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalide Username or Password.
        /// </summary>
        public static string InvalidUsernameorPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invaled Captcha.
        /// </summary>
        public static string InvaliedCaptcha {
            get {
                return ResourceManager.GetString("InvaliedCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalied Password.
        /// </summary>
        public static string InvaliedPass {
            get {
                return ResourceManager.GetString("InvaliedPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length is 20 charachters.
        /// </summary>
        public static string LastNameLength {
            get {
                return ResourceManager.GetString("LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is Required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the link you pressed is already Expired please make another Reset Password Request.
        /// </summary>
        public static string LinkExpired {
            get {
                return ResourceManager.GetString("LinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number isn&apos;t Valied.
        /// </summary>
        public static string MobileNoisNotValied {
            get {
                return ResourceManager.GetString("MobileNoisNotValied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number is Required.
        /// </summary>
        public static string MobileNoRequired {
            get {
                return ResourceManager.GetString("MobileNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Didn&apos;t Make any orders today.
        /// </summary>
        public static string NoOrders {
            get {
                return ResourceManager.GetString("NoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is No Results for your search.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but you aren&apos;t authorized to access this page.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t the amout you want to sell, you only have.
        /// </summary>
        public static string NotEnough {
            get {
                return ResourceManager.GetString("NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Created Successfully.
        /// </summary>
        public static string OrderCreated {
            get {
                return ResourceManager.GetString("OrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string OrderDateTime {
            get {
                return ResourceManager.GetString("OrderDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Failed to be Created please try again with valid Information.
        /// </summary>
        public static string OrderFailed {
            get {
                return ResourceManager.GetString("OrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIrder Number:.
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Price.
        /// </summary>
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password isn&apos;t Valied &quot;Minimum eight and maximum 10 characters, at least one uppercase letter, one lowercase letter, one number and one special character:&quot;&quot;.
        /// </summary>
        public static string PasswordNotValied {
            get {
                return ResourceManager.GetString("PasswordNotValied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that you can only update the quantity of the order not the Stock and not the.
        /// </summary>
        public static string QuantityNotStock {
            get {
                return ResourceManager.GetString("QuantityNotStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question is Required.
        /// </summary>
        public static string QuestionRequired {
            get {
                return ResourceManager.GetString("QuestionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Done.
        /// </summary>
        public static string RegisteredDone {
            get {
                return ResourceManager.GetString("RegisteredDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selec tUser:.
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUP {
            get {
                return ResourceManager.GetString("SignUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock:.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Name.
        /// </summary>
        public static string StockName {
            get {
                return ResourceManager.GetString("StockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Number:.
        /// </summary>
        public static string StockNum {
            get {
                return ResourceManager.GetString("StockNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock pic.
        /// </summary>
        public static string StockPic {
            get {
                return ResourceManager.GetString("StockPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Price.
        /// </summary>
        public static string StockPrice {
            get {
                return ResourceManager.GetString("StockPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Quantity.
        /// </summary>
        public static string StockQuantity {
            get {
                return ResourceManager.GetString("StockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Orders.
        /// </summary>
        public static string TodayOrders {
            get {
                return ResourceManager.GetString("TodayOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Stock Prices.
        /// </summary>
        public static string TodayStockPrices {
            get {
                return ResourceManager.GetString("TodayStockPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Shares Values :.
        /// </summary>
        public static string TotalSharesValues {
            get {
                return ResourceManager.GetString("TotalSharesValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnBlock.
        /// </summary>
        public static string UnBlock {
            get {
                return ResourceManager.GetString("UnBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry But This user name doesn&apos;t Exist.
        /// </summary>
        public static string UNNotExist {
            get {
                return ResourceManager.GetString("UNNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length is 20 charachters.
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is Required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This isn&apos;t your answer.
        /// </summary>
        public static string WrongAnswer {
            get {
                return ResourceManager.GetString("WrongAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry ,This isn&apos;t your E-mail .
        /// </summary>
        public static string WrongMail {
            get {
                return ResourceManager.GetString("WrongMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Locked !!.
        /// </summary>
        public static string YouAreLocked {
            get {
                return ResourceManager.GetString("YouAreLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have No Orders !.
        /// </summary>
        public static string YouHaveNoOrders {
            get {
                return ResourceManager.GetString("YouHaveNoOrders", resourceCulture);
            }
        }
    }
}
